Name: Testing workflow variables

on:
    workflow_dispatch
env:
  cloud: Azure

jobs:
  Greeting_Jon:
    runs-on:  ubuntu-latest
    env:
      greeting: Hello
    steps:
      -name: "Hey Its Monday"
       run: echo"$greeting$First_Name is using $cloud"
       env:
       First_Name: Ravi
