name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Display Artifact
      run: |
        echo "Build Artifacts:"
        ls -la target/*.jar
        echo "---"
        
    - name: Find Main JAR File
      id: find_jar
      run: |
        # Find the main JAR (excluding *-sources.jar and *-tests.jar)
        MAIN_JAR=$(ls target/*.jar | grep -v -e sources -e tests | head -1)
        echo "main_jar=$MAIN_JAR" >> $GITHUB_OUTPUT
        echo "Selected JAR: $MAIN_JAR"
        
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: ${{ steps.find_jar.outputs.main_jar }}
        retention-days: 1

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest 
    needs: build-test
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch
    
    steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v3
      with:
        name: java-app
        
    - name: List downloaded files
      run: ls -la
      
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ needs.build-test.outputs.main_jar || '*.jar' }}
